sudo: false
# sudo: required
# dist: trusty

language: java

# test the server on multiple JDKs
jdk:
  - oraclejdk8
  #- oraclejdk7

python:
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.5"

# addons:
#   hosts:
#     - localhost

before_install:
  - pip install -U pip setuptools
  - pip install coveralls
  # show java version
  - java -version
  # start server as an experiment
  - wget http://www.cs.arizona.edu/~hahnpowell/processors-server/current/processors-server.jar
  - export PROCESSORS_SERVER="$(pwd)/processors-server.jar"
  - java -Xmx3G -jar processors-server.jar NLPServer 8886

# command to install dependencies
install:
  - pip install .
#  - pip install git+https://github.com/myedibleenso/py-processors.git
# cache:
#   pip: true
#   timeout: 1000

# command to run tests
script:
  #- green -vv --run-coverage processors/tests/testserialization.py
  - green -vv --run-coverage

after_success:
  # inspect log file
  - cat ~/.py-processors.log
  - coveralls
