#sudo: false
sudo: required

language: python

python:
  # - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.5"

before_install:
  - pip install -U pip setuptools

# command to install dependencies
install:
  - pip install -v .
#  - pip install -v git+https://github.com/myedibleenso/py-processors.git
# cache:
#   pip: true
#   timeout: 1000

# command to run tests
script:
  - green -vv --run-coverage

after_success:
  - coveralls
